export const Icons = {
	add: 'plus-circle',
	armFlex: 'arm-flex',
	book: 'book-open-page-variant',
	bread: 'baguette',
	brightness7: 'brightness-7',
	bullseye: 'bullseye-arrow',
	collect: 'rhombus-split',
	critical: 'sword-cross',
	dagger: 'knife-military',
	default: 'cancel',
	earth: 'earth',
	hand: 'hand',
	handPointRight: 'hand-pointing-right',
	personHeart: 'account-heart',
	personRegen: 'account-convert',
	personShadow: 'account-multiple-outline',
	shield: 'shield',
	shieldHome: 'shield-home',
	shieldElement: 'shield-sun',
	shieldPerson: 'shield-account',
	shieldPlus: 'shield-plus',
	speedometer: 'speedometer',
	melee: 'sword',
	pistol: 'pistol',
	plus: 'account-plus',
	potion: 'bottle-tonic-plus-outline',
	reload: 'reload',
	run: 'run',
	runFast: 'run-fast',
	subtract: 'minus-circle',
	target: 'target',
	targetPerson: 'target-account',
	team: 'account-group',
	will: 'human-handsup'
};

export default Icons;
